apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: completions.copilot.poc.com
spec:
  group: copilot.poc.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              userPrompt:
                type: string
            required:
            - userPrompt
          status:
            type: object
            properties:
              completion:
                type: string
                description: The completion of the user prompt.
  scope: Cluster
  names:
    plural: completions
    singular: completion
    kind: Completion
    shortNames:
    - cpln