# permissions for end users to edit completions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: completion-editor-role
rules:
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions/status
  verbs:
  - get
