# permissions for end users to view completions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: completion-viewer-role
rules:
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions/status
  verbs:
  - get
