
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions/finalizers
  verbs:
  - update
- apiGroups:
  - complete.yaml-copilot.com
  resources:
  - completions/status
  verbs:
  - get
  - patch
  - update
