name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - ".github/workflows/bot.yaml"
      - ".github/workflows/todo-issue.yaml"

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "data-lab/**"
      - ".github/workflows/bot.yaml"
      - ".github/workflows/todo-issue.yaml"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make test
        name: Run tests and generate coverage report
        shell: bash
      - uses: codecov/codecov-action@v3
        with:
          files: ./cover.out
          fail_ci_if_error: true
      - run: go vet -v ./...
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go build -o copilot-ops-linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64
      - run: go build -o copilot-ops-linux-arm64
        env:
          GOOS: linux
          GOARCH: arm64
      - run: go build -o copilot-ops-darwin-amd64
        env:
          GOOS: darwin
          GOARCH: amd64
      - run: go build -o copilot-ops-darwin-arm64
        env:
          GOOS: darwin
          GOARCH: arm64

      - uses: actions/upload-artifact@v3
        with:
          name: copilot-ops-linux-amd64
          path: copilot-ops-linux-amd64
      - uses: actions/upload-artifact@v3
        with:
          name: copilot-ops-linux-arm64
          path: copilot-ops-linux-arm64
      - uses: actions/upload-artifact@v3
        with:
          name: copilot-ops-darwin-amd64
          path: copilot-ops-darwin-amd64
      - uses: actions/upload-artifact@v3
        with:
          name: copilot-ops-darwin-arm64
          path: copilot-ops-darwin-arm64
